In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense, Dropout
from keras.utils import np_utils
from keras.layers import Dense
from keras.models import Model
from keras.callbacks import EarlyStopping, TensorBoard

Using TensorFlow backend.
/usr/local/var/pyenv/versions/anaconda3-5.2.0/envs/ml/lib/python3.6/site-packages/requests/__init__.py:91: RequestsDependencyWarning: urllib3 (1.24.1) or chardet (3.0.4) doesn't match a supported version!
  RequestsDependencyWarning)


In [2]:
def binary_encode(i, num_digits):
    return np.array([i >> d & 1 for d in range(num_digits)])

NUM_DIGITS = 9
trX = np.array([binary_encode(i, NUM_DIGITS) for i in range(101, 2 ** NUM_DIGITS)])
print(len(trX))
print(trX)

411
[[1 0 1 ... 1 0 0]
 [0 1 1 ... 1 0 0]
 [1 1 1 ... 1 0 0]
 ...
 [1 0 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [3]:
def fizz_buzz_encode(i):
    if   i % 15 == 0: return np.array([0, 0, 0, 1]) #fizzbuzz
    elif i % 5  == 0: return np.array([0, 0, 1, 0]) #buzz
    elif i % 3  == 0: return np.array([0, 1, 0, 0]) #fizz
    else:             return np.array([1, 0, 0, 0])

trY = np.array([fizz_buzz_encode(i) for i in range(101, 2 ** NUM_DIGITS)])
print(len(trY))
print(trY)

411
[[1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 ...
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]]


In [4]:
model = Sequential()
es_default = EarlyStopping()
model.add(Dense(1000, input_dim=NUM_DIGITS, activation="relu"))
model.add(Dense(1000, activation="relu"))
model.add(Dropout(0.5))
model.add(Dense(200, activation="relu"))
model.add(Dense(4, activation="softmax"))
model.compile(loss='categorical_crossentropy', optimizer='adam', metrics=["accuracy"])
board_cb = TensorBoard(log_dir='./logs', histogram_freq=1)
cbks = [board_cb]
model.fit(trX, trY, epochs=150, batch_size=128, validation_split=0.1, callbacks=cbks)

Train on 369 samples, validate on 42 samples
Epoch 1/150
369/369 [==============================] - 0s 489us/step - loss: 1.2811 - acc: 0.3848 - val_loss: 1.2124 - val_acc: 0.5238
Epoch 2/150
369/369 [==============================] - 0s 244us/step - loss: 1.1837 - acc: 0.5366 - val_loss: 1.2372 - val_acc: 0.5238
Epoch 3/150
369/369 [==============================] - 0s 281us/step - loss: 1.1541 - acc: 0.5393 - val_loss: 1.1830 - val_acc: 0.5238
Epoch 4/150
369/369 [==============================] - 0s 307us/step - loss: 1.1447 - acc: 0.5366 - val_loss: 1.1628 - val_acc: 0.5238
Epoch 5/150
369/369 [==============================] - 0s 300us/step - loss: 1.1329 - acc: 0.5366 - val_loss: 1.1749 - val_acc: 0.5238
Epoch 6/150
369/369 [==============================] - 0s 315us/step - loss: 1.1385 - acc: 0.5366 - val_loss: 1.1960 - val_acc: 0.5238
Epoch 7/150
369/369 [==============================] - 0s 303us/step - loss: 1.1321 - acc: 0.5366 - val_loss: 1.1805 - val_acc: 0.5238
Epoch 8/15

Epoch 61/150
369/369 [==============================] - 0s 402us/step - loss: 0.0443 - acc: 0.9946 - val_loss: 0.6875 - val_acc: 0.7619
Epoch 62/150
369/369 [==============================] - 0s 259us/step - loss: 0.0387 - acc: 0.9973 - val_loss: 0.8381 - val_acc: 0.5952
Epoch 63/150
369/369 [==============================] - 0s 260us/step - loss: 0.0328 - acc: 0.9973 - val_loss: 0.6192 - val_acc: 0.7857
Epoch 64/150
369/369 [==============================] - 0s 263us/step - loss: 0.0302 - acc: 0.9973 - val_loss: 0.5850 - val_acc: 0.8333
Epoch 65/150
369/369 [==============================] - 0s 262us/step - loss: 0.0316 - acc: 0.9973 - val_loss: 0.6431 - val_acc: 0.7857
Epoch 66/150
369/369 [==============================] - 0s 247us/step - loss: 0.0228 - acc: 1.0000 - val_loss: 0.7779 - val_acc: 0.6429
Epoch 67/150
369/369 [==============================] - 0s 267us/step - loss: 0.0245 - acc: 0.9973 - val_loss: 0.6327 - val_acc: 0.7381
Epoch 68/150
369/369 [==========================

369/369 [==============================] - 0s 274us/step - loss: 0.0020 - acc: 1.0000 - val_loss: 0.5320 - val_acc: 0.8571
Epoch 122/150
369/369 [==============================] - 0s 247us/step - loss: 0.0020 - acc: 1.0000 - val_loss: 0.5092 - val_acc: 0.8810
Epoch 123/150
369/369 [==============================] - 0s 267us/step - loss: 0.0022 - acc: 1.0000 - val_loss: 0.5005 - val_acc: 0.8810
Epoch 124/150
369/369 [==============================] - 0s 270us/step - loss: 0.0019 - acc: 1.0000 - val_loss: 0.5030 - val_acc: 0.8571
Epoch 125/150
369/369 [==============================] - 0s 241us/step - loss: 0.0023 - acc: 1.0000 - val_loss: 0.5129 - val_acc: 0.8333
Epoch 126/150
369/369 [==============================] - 0s 409us/step - loss: 0.0020 - acc: 1.0000 - val_loss: 0.5089 - val_acc: 0.8333
Epoch 127/150
369/369 [==============================] - 0s 272us/step - loss: 0.0017 - acc: 1.0000 - val_loss: 0.5067 - val_acc: 0.8333
Epoch 128/150
369/369 [==============================] 

In [5]:
def fizz_buzz(i, prediction):
    return [str(i), "fizz", "buzz", "fizzbuzz"][prediction]
numbers = np.arange(101)
teX = np.transpose(binary_encode(numbers, NUM_DIGITS))
teY = model.predict_classes(teX)
output = np.vectorize(fizz_buzz)(numbers, teY)
print (output)


answer = np.array([])
for i in numbers:
    if i % 15 == 0: answer = np.append(answer, "fizzbuzz")
    elif i % 5 == 0: answer = np.append(answer, "buzz")
    elif i % 3 == 0: answer = np.append(answer, "fizz")
    else: answer = np.append(answer, str(i))

evaluate = np.array(answer == output)
print (np.count_nonzero(evaluate == True) / 100)

['fizz' '1' '2' 'fizz' '4' '5' 'fizz' '7' '8' 'fizz' 'buzz' '11' 'fizz'
 '13' '14' '15' '16' '17' 'fizz' '19' '20' '21' '22' '23' 'fizz' 'buzz'
 '26' 'fizz' '28' '29' 'fizzbuzz' '31' '32' '33' 'fizz' '35' 'fizz' '37'
 'fizz' '39' '40' '41' 'fizz' '43' '44' 'fizzbuzz' '46' '47' 'fizz' '49'
 'fizz' 'fizz' '52' '53' 'fizz' '55' '56' 'fizz' '58' '59' 'fizzbuzz' '61'
 '62' 'fizz' '64' '65' 'fizz' '67' '68' 'fizz' '70' '71' 'fizz' '73' '74'
 'fizzbuzz' '76' '77' 'fizz' '79' '80' 'fizz' '82' '83' 'fizz' 'buzz' '86'
 'fizz' '88' '89' 'fizzbuzz' '91' '92' 'fizz' '94' 'buzz' '96' '97' 'fizz'
 'fizz' '100']
0.82
