In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from keras.layers import Dense
from keras.models import Model

Using TensorFlow backend.
/usr/local/var/pyenv/versions/anaconda3-5.2.0/envs/ml/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
def binary_encode(i, num_digits):
    return np.array([i >> d & 1 for d in range(num_digits)])

NUM_DIGITS = 8
trX = np.array([binary_encode(i, NUM_DIGITS) for i in range(101, 2 ** NUM_DIGITS)])
print(len(trX))

155


In [4]:
def fizz_buzz_encode(i):
    if   i % 15 == 0: return np.array([0, 0, 0, 1]) #fizzbuzz
    elif i % 5  == 0: return np.array([0, 0, 1, 0]) #buzz
    elif i % 3  == 0: return np.array([0, 1, 0, 0]) #fizz
    else:             return np.array([1, 0, 0, 0])

trY = np.array([fizz_buzz_encode(i) for i in range(101, 2 ** NUM_DIGITS)])
print(len(trY))
print(trY)

155
[[1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 0 0 1]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 [0 0 1 0]
 [0 1 0 0]
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]
 [0 0 1 0]
 [1 0 

In [5]:
model = Sequential()
model.add(Dense(1000, input_dim=8, activation="relu"))
model.add(Dense(1000, activation="relu"))
model.add(Dense(4, activation="softmax"))
model.compile(loss='categorical_crossentropy', optimizer='adagrad', metrics=["accuracy"])
model.fit(trX, trY, epochs=100, batch_size=128)

Epoch 1/100
155/155 [==============================] - 0s 2ms/step - loss: 1.7821 - acc: 0.3677
Epoch 2/100
155/155 [==============================] - 0s 188us/step - loss: 1.4420 - acc: 0.2839
Epoch 3/100
155/155 [==============================] - 0s 221us/step - loss: 1.1381 - acc: 0.5355
Epoch 4/100
155/155 [==============================] - 0s 248us/step - loss: 1.1316 - acc: 0.5484
Epoch 5/100
155/155 [==============================] - 0s 249us/step - loss: 1.1185 - acc: 0.5355
Epoch 6/100
155/155 [==============================] - 0s 221us/step - loss: 1.0765 - acc: 0.5355
Epoch 7/100
155/155 [==============================] - 0s 283us/step - loss: 1.0679 - acc: 0.5419
Epoch 8/100
155/155 [==============================] - 0s 247us/step - loss: 1.0489 - acc: 0.5419
Epoch 9/100
155/155 [==============================] - 0s 254us/step - loss: 1.0263 - acc: 0.5484
Epoch 10/100
155/155 [==============================] - 0s 223us/step - loss: 1.0092 - acc: 0.5419
Epoch 11/100
155/155 

In [6]:
def fizz_buzz(i, prediction):
    return [str(i), "fizz", "buzz", "fizzbuzz"][prediction]
numbers = np.arange(1, 101)
teX = np.transpose(binary_encode(numbers, NUM_DIGITS))
teY = model.predict_classes(teX)
output = np.vectorize(fizz_buzz)(numbers, teY)
print (output)


answer = np.array([])
for i in numbers:
    if i % 15 == 0: answer = np.append(answer, "fizzbuzz")
    elif i % 5 == 0: answer = np.append(answer, "buzz")
    elif i % 3 == 0: answer = np.append(answer, "fizz")
    else: answer = np.append(answer, str(i))
print (answer)

evaluate = np.array(answer == output)
print (np.count_nonzero(evaluate == True) / 100)

['1' '2' '3' '4' '5' '6' '7' '8' '9' '10' '11' 'fizz' '13' '14' '15' '16'
 'buzz' '18' 'buzz' '20' '21' '22' '23' '24' 'buzz' '26' 'fizz' '28' '29'
 '30' '31' '32' '33' 'fizz' '35' '36' '37' '38' '39' '40' '41' 'fizz'
 'fizz' '44' '45' 'fizz' '47' '48' '49' '50' 'fizz' '52' '53' '54' '55'
 '56' 'fizz' 'fizz' 'fizz' '60' '61' '62' 'fizz' '64' '65' '66' '67' '68'
 '69' '70' '71' '72' '73' '74' '75' 'buzz' 'buzz' 'fizz' '79' '80' '81'
 '82' 'buzz' '84' 'buzz' '86' '87' '88' '89' '90' '91' 'buzz' 'buzz' '94'
 '95' '96' '97' '98' '99' '100']
['1' '2' 'fizz' '4' 'buzz' 'fizz' '7' '8' 'fizz' 'buzz' '11' 'fizz' '13'
 '14' 'fizzbuzz' '16' '17' 'fizz' '19' 'buzz' 'fizz' '22' '23' 'fizz'
 'buzz' '26' 'fizz' '28' '29' 'fizzbuzz' '31' '32' 'fizz' '34' 'buzz'
 'fizz' '37' '38' 'fizz' 'buzz' '41' 'fizz' '43' '44' 'fizzbuzz' '46' '47'
 'fizz' '49' 'buzz' 'fizz' '52' '53' 'fizz' 'buzz' '56' 'fizz' '58' '59'
 'fizzbuzz' '61' '62' 'fizz' '64' 'buzz' 'fizz' '67' '68' 'fizz' 'buzz'
 '71' 'fizz' '73' '74' '