In [1]:
import numpy as np
from keras.models import Sequential
from keras.layers import Dense
from keras.utils import np_utils
from keras.layers import Dense
from keras.models import Model

Using TensorFlow backend.
/usr/local/var/pyenv/versions/anaconda3-5.2.0/envs/ml/lib/python3.6/importlib/_bootstrap.py:219: RuntimeWarning: compiletime version 3.5 of module 'tensorflow.python.framework.fast_tensor_util' does not match runtime version 3.6
  return f(*args, **kwds)


In [2]:
def binary_encode(i, num_digits):
    return np.array([i >> d & 1 for d in range(num_digits)])

NUM_DIGITS = 10
trX = np.array([binary_encode(i, NUM_DIGITS) for i in range(101, 2 ** NUM_DIGITS)])
print(len(trX))
print(trX)

923
[[1 0 1 ... 0 0 0]
 [0 1 1 ... 0 0 0]
 [1 1 1 ... 0 0 0]
 ...
 [1 0 1 ... 1 1 1]
 [0 1 1 ... 1 1 1]
 [1 1 1 ... 1 1 1]]


In [3]:
def fizz_buzz_encode(i):
    if   i % 15 == 0: return np.array([0, 0, 0, 1]) #fizzbuzz
    elif i % 5  == 0: return np.array([0, 0, 1, 0]) #buzz
    elif i % 3  == 0: return np.array([0, 1, 0, 0]) #fizz
    else:             return np.array([1, 0, 0, 0])

trY = np.array([fizz_buzz_encode(i) for i in range(101, 2 ** NUM_DIGITS)])
print(len(trY))
print(trY)

923
[[1 0 0 0]
 [0 1 0 0]
 [1 0 0 0]
 ...
 [1 0 0 0]
 [1 0 0 0]
 [0 1 0 0]]


In [5]:
model = Sequential()
model.add(Dense(1000, input_dim=NUM_DIGITS, activation="relu"))
model.add(Dense(1000, activation="relu"))
model.add(Dense(4, activation="softmax"))
model.compile(loss='categorical_crossentropy', optimizer='adagrad', metrics=["accuracy"])
model.fit(trX, trY, epochs=100, batch_size=128)

Epoch 1/100
923/923 [==============================] - 0s 399us/step - loss: 1.9104 - acc: 0.5060
Epoch 2/100
923/923 [==============================] - 0s 153us/step - loss: 1.1448 - acc: 0.5341
Epoch 3/100
923/923 [==============================] - 0s 137us/step - loss: 1.1413 - acc: 0.5341
Epoch 4/100
923/923 [==============================] - 0s 154us/step - loss: 1.1346 - acc: 0.5341
Epoch 5/100
923/923 [==============================] - 0s 146us/step - loss: 1.1246 - acc: 0.5341
Epoch 6/100
923/923 [==============================] - 0s 152us/step - loss: 1.1154 - acc: 0.5341
Epoch 7/100
923/923 [==============================] - 0s 156us/step - loss: 1.1057 - acc: 0.5341
Epoch 8/100
923/923 [==============================] - 0s 165us/step - loss: 1.0900 - acc: 0.5330
Epoch 9/100
923/923 [==============================] - 0s 165us/step - loss: 1.0738 - acc: 0.5320
Epoch 10/100
923/923 [==============================] - 0s 157us/step - loss: 1.0568 - acc: 0.5352
Epoch 11/100
923/92

923/923 [==============================] - 0s 167us/step - loss: 0.0363 - acc: 0.9989
Epoch 84/100
923/923 [==============================] - 0s 157us/step - loss: 0.0332 - acc: 0.9989
Epoch 85/100
923/923 [==============================] - 0s 156us/step - loss: 0.0351 - acc: 1.0000
Epoch 86/100
923/923 [==============================] - 0s 146us/step - loss: 0.0317 - acc: 0.9989
Epoch 87/100
923/923 [==============================] - 0s 140us/step - loss: 0.0306 - acc: 0.9989
Epoch 88/100
923/923 [==============================] - 0s 138us/step - loss: 0.0296 - acc: 0.9989
Epoch 89/100
923/923 [==============================] - 0s 136us/step - loss: 0.0316 - acc: 1.0000
Epoch 90/100
923/923 [==============================] - 0s 145us/step - loss: 0.0285 - acc: 1.0000
Epoch 91/100
923/923 [==============================] - 0s 155us/step - loss: 0.0274 - acc: 1.0000
Epoch 92/100
923/923 [==============================] - 0s 139us/step - loss: 0.0267 - acc: 1.0000
Epoch 93/100
923/923 [=

In [6]:
def fizz_buzz(i, prediction):
    return [str(i), "fizz", "buzz", "fizzbuzz"][prediction]
numbers = np.arange(1, 101)
teX = np.transpose(binary_encode(numbers, NUM_DIGITS))
teY = model.predict_classes(teX)
output = np.vectorize(fizz_buzz)(numbers, teY)
print (output)


answer = np.array([])
for i in numbers:
    if i % 15 == 0: answer = np.append(answer, "fizzbuzz")
    elif i % 5 == 0: answer = np.append(answer, "buzz")
    elif i % 3 == 0: answer = np.append(answer, "fizz")
    else: answer = np.append(answer, str(i))
print (answer)

evaluate = np.array(answer == output)
print (np.count_nonzero(evaluate == True) / 100)

['1' '2' 'fizz' '4' '5' 'fizz' '7' '8' 'fizz' 'buzz' '11' 'fizz' '13' '14'
 'fizzbuzz' '16' '17' 'fizz' '19' '20' 'fizz' '22' '23' 'fizz' 'buzz' '26'
 'fizz' '28' '29' 'fizzbuzz' '31' '32' 'fizz' '34' 'buzz' 'fizz' '37' '38'
 'fizz' 'buzz' '41' 'fizz' '43' '44' 'fizzbuzz' '46' '47' 'fizz' '49'
 'buzz' 'fizz' '52' '53' 'fizz' 'buzz' '56' 'fizz' '58' '59' 'fizzbuzz'
 '61' '62' 'fizz' '64' 'buzz' 'fizz' '67' '68' 'fizz' 'buzz' '71' 'fizz'
 '73' '74' 'fizzbuzz' 'buzz' '77' 'fizz' '79' '80' '81' '82' '83' 'fizz'
 'buzz' '86' 'fizz' '88' '89' 'fizzbuzz' '91' '92' 'fizz' '94' 'buzz'
 'fizz' '97' '98' 'fizz' 'buzz']
['1' '2' 'fizz' '4' 'buzz' 'fizz' '7' '8' 'fizz' 'buzz' '11' 'fizz' '13'
 '14' 'fizzbuzz' '16' '17' 'fizz' '19' 'buzz' 'fizz' '22' '23' 'fizz'
 'buzz' '26' 'fizz' '28' '29' 'fizzbuzz' '31' '32' 'fizz' '34' 'buzz'
 'fizz' '37' '38' 'fizz' 'buzz' '41' 'fizz' '43' '44' 'fizzbuzz' '46' '47'
 'fizz' '49' 'buzz' 'fizz' '52' '53' 'fizz' 'buzz' '56' 'fizz' '58' '59'
 'fizzbuzz' '61' '62' '